### ISSUE TITLE
mull-cxx: Address Sanitizer crashes at the start in libEBC related code

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#531]
I am using the `fmt` example from the README page. Here is the stacktrace:

```
./fmt.sh
++ /tmp/build.mull.clion.dir/tools/driver-cxx/mull-cxx -test-framework=GoogleTest -mutators=default -compdb-path compile_commands.json '-compilation-flags=    -isystem /opt/llvm/7.0.0/include/c++/v1     -isystem /opt/llvm-7.0.0/lib/clang/7.0.0/include/     -isystem /opt/llvm-7.0.0/include/c++/v1     -isystem /usr/include' ./bin/core-test
Extracting bitcode from executable (threads: 1): 0/1=================================================================
==82599==ERROR: AddressSanitizer: container-overflow on address 0x608000001a68 at pc 0x0001061a56df bp 0x7ffeedd97f70 sp 0x7ffeedd97720
READ of size 24 at 0x608000001a68 thread T0
    #0 0x1061a56de in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x596de)
    #1 0x101e84656 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) string:1854
    #2 0x101e845cc in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) string:1855
    #3 0x101e9a0e0 in void std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::construct<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) memory:1825
    #4 0x101e9a08f in void std::__1::allocator_traits<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__construct<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) memory:1717
    #5 0x101e99fb9 in void std::__1::allocator_traits<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::construct<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) memory:1560
    #6 0x101e99aa8 in void std::__1::allocator_traits<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__construct_backward<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*>(std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*&) memory:1679
    #7 0x101e98dea in std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__swap_out_circular_buffer(std::__1::__split_buffer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&>&) vector:931
    #8 0x101ef23fb in void std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__push_back_slow_path<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) vector:1615
    #9 0x101f03d58 in std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::push_back(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) vector:1652
    #10 0x101f03beb in ebc::util::xml::GetTextFromNodesWithName(_xmlNode*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) Xml.cpp:56
    #11 0x101ee7c18 in ebc::BitcodeMetadata::GetCommands(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const BitcodeMetadata.cpp:82
    #12 0x101ee7d17 in ebc::BitcodeMetadata::GetClangCommands(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const BitcodeMetadata.cpp:89
    #13 0x101edc1c6 in ebc::BitcodeArchive::GetRawEmbeddedFiles() const BitcodeArchive.cpp:127
    #14 0x101ea2b88 in main::$_0::operator()() const driver-cxx.cpp:229
    #15 0x101ea275c in decltype(std::__1::forward<main::$_0&>(fp)()) std::__1::__invoke<main::$_0&>(main::$_0&&&) type_traits:4339
    #16 0x101ea270c in void std::__1::__invoke_void_return_wrapper<void>::__call<main::$_0&>(main::$_0&&&) __functional_base:349
    #17 0x101e9f690 in std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, void ()>::operator()() functional:1562
    #18 0x101e84add in std::__1::function<void ()>::operator()() const functional:1913
    #19 0x101e6c2d5 in mull::TaskExecutor<mull::SingleTaskTag>::execute() TaskExecutor.h:115
    #20 0x101e6a831 in main driver-cxx.cpp:237
    #21 0x7fff61c64ed8 in start (libdyld.dylib:x86_64+0x16ed8)

0x608000001a68 is located 72 bytes inside of 96-byte region [0x608000001a20,0x608000001a80)
allocated by thread T0 here:
    #0 0x1061b4b92 in wrap__Znwm (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x68b92)
    #1 0x101e75d28 in std::__1::__libcpp_allocate(unsigned long, unsigned long) new:252
    #2 0x101e998b3 in std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::allocate(unsigned long, void const*) memory:1813
    #3 0x101e99740 in std::__1::allocator_traits<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::allocate(std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, unsigned long) memory:1546
    #4 0x101e994fb in std::__1::__split_buffer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&) __split_buffer:311
    #5 0x101e98d1c in std::__1::__split_buffer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&) __split_buffer:310
    #6 0x101ef23ac in void std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__push_back_slow_path<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) vector:1611
    #7 0x101f03d58 in std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::push_back(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) vector:1652
    #8 0x101f03beb in ebc::util::xml::GetTextFromNodesWithName(_xmlNode*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) Xml.cpp:56
    #9 0x101ee7c18 in ebc::BitcodeMetadata::GetCommands(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const BitcodeMetadata.cpp:82
    #10 0x101ee7d17 in ebc::BitcodeMetadata::GetClangCommands(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const BitcodeMetadata.cpp:89
    #11 0x101edc1c6 in ebc::BitcodeArchive::GetRawEmbeddedFiles() const BitcodeArchive.cpp:127
    #12 0x101ea2b88 in main::$_0::operator()() const driver-cxx.cpp:229
    #13 0x101ea275c in decltype(std::__1::forward<main::$_0&>(fp)()) std::__1::__invoke<main::$_0&>(main::$_0&&&) type_traits:4339
    #14 0x101ea270c in void std::__1::__invoke_void_return_wrapper<void>::__call<main::$_0&>(main::$_0&&&) __functional_base:349
    #15 0x101e9f690 in std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, void ()>::operator()() functional:1562
    #16 0x101e84add in std::__1::function<void ()>::operator()() const functional:1913
    #17 0x101e6c2d5 in mull::TaskExecutor<mull::SingleTaskTag>::execute() TaskExecutor.h:115
    #18 0x101e6a831 in main driver-cxx.cpp:237
    #19 0x7fff61c64ed8 in start (libdyld.dylib:x86_64+0x16ed8)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x596de) in __asan_memcpy
Shadow bytes around the buggy address:
  0x1c10000002f0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x1c1000000300: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x1c1000000310: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x1c1000000320: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x1c1000000330: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 fa
=>0x1c1000000340: fa fa fa fa 00 00 00 00 00 00 00 00 00[fc]fc fc
  0x1c1000000350: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1000000360: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1000000370: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1000000380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c1000000390: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==82599==ABORTING
./fmt.sh: line 11: 82599 Abort trap: 6           /tmp/build.mull.clion.dir/tools/driver-cxx/mull-cxx -test-framework=GoogleTest -mutators=default -compdb-path compile_commands.json -compilation-flags="    -isystem /opt/llvm/7.0.0/include/c++/v1     -isystem /opt/llvm-7.0.0/lib/clang/7.0.0/include/     -isystem /opt/llvm-7.0.0/include/c++/v1     -isystem /usr/include" ./bin/core-test
++ false
```

This is how I enabled Address Sanitizer:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8efdbb3..6b3ae44 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -140,7 +140,7 @@ endif()

 set(MULL_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

-set (MULL_CXX_FLAGS "-std=c++11 -fPIC -fvisibility-inlines-hidden -fno-exceptions")
+set (MULL_CXX_FLAGS "-std=c++11 -fPIC -fvisibility-inlines-hidden -fno-exceptions -fsanitize=address")
 if (NOT LLVM_ENABLE_RTTI)
   set(MULL_CXX_FLAGS "${MULL_CXX_FLAGS} -fno-rtti")
 endif()
@@ -148,7 +148,7 @@ if (MULL_BUILD_32_BITS)
   set(MULL_CXX_FLAGS "${MULL_CXX_FLAGS} -m32")
 endif()

-set (MULL_LINK_FLAGS "-rdynamic")
+set (MULL_LINK_FLAGS "-rdynamic -fsanitize=address")
 if (MULL_BUILD_32_BITS)
   set(MULL_LINK_FLAGS "${MULL_LINK_FLAGS} -m32")
 endif()
```

**Comment by stanislaw** [comment]
This seems to be a duplicate of #614.
