### ISSUE TITLE
Mull segfaults on generation mutants for postgres

### ISSUE THREAD

**Issue by ligurio** [mull-project/mull#859]
## How to reproduce
```
$ git clone https://github.com/postgres/postgres
$ git reset --hard 59773da2b132ced19c84ff1f69b53b5cf95fd69e
$ CC=clang CXX=clang++ CXXFLAGS="-fembed-bitcode -g" CFLAGS="-fembed-bitcode -g" ./configure
$ mull-cxx src/backend/postgres
```

## Actual result
```
<snipped>
[warning] Cannot parse file: '/home/sergeyb/sources/postgres/src/backend/utils/adt/like_support.c':
mull-cxx /home/sergeyb/sources/postgres/src/backend/utils/adt/like_support.c 
Make sure that the flags provided to Mull are the same flags that are used for normal compilation.
       [################################] 169603/169603. Finished in 7727ms
[info] Prepare mutations (threads: 1)
       [################################] 1/1. Finished in 2ms
[info] Cloning functions for mutation (threads: 8)
       [--------------------------------] 13/760Segmentation fault (core dumped)
```
or 
```
<snipped>
[info] Prepare mutations (threads: 1)
       [################################] 1/1. Finished in 3ms
[info] Cloning functions for mutation (threads: 8)
       [################################] 760/760. Finished in 5356ms
[info] Removing original functions (threads: 8)
       [--------------------------------] 11/760Segmentation fault (core dumped)
```

when running under GDB:
```
[info] Prepare mutations (threads: 1)
       [################################] 1/1. Finished in 3ms[New Thread 0x7ffff0990700 (LWP 25442)]
[New Thread 0x7ffff3195700 (LWP 25443)]
[New Thread 0x7ffff3996700 (LWP 25444)]
[New Thread 0x7ffff4197700 (LWP 25445)]
[New Thread 0x7ffff4998700 (LWP 25446)]
[New Thread 0x7ffff2994700 (LWP 25447)]
[New Thread 0x7ffff2193700 (LWP 25448)]
[New Thread 0x7ffff1992700 (LWP 25449)]

[info] Cloning functions for mutation (threads: 8)
[New Thread 0x7fff83fff700 (LWP 25450)]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 75 "mull-cxx" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3195700 (LWP 25443)]
0x00000000029c0723 in llvm::ValueHandleBase::AddToUseList() ()
(gdb) 
(gdb) bt
#0  0x00000000029c0723 in llvm::ValueHandleBase::AddToUseList() ()
#1  0x00000000024e7458 in llvm::CloneFunction(llvm::Function*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false> > >&, llvm::ClonedCodeInfo*) ()
#2  0x00000000009d3603 in mull::CloneMutatedFunctionsTask::cloneFunctions(mull::Bitcode&) ()
#3  0x00000000009d3538 in mull::CloneMutatedFunctionsTask::operator()(__gnu_cxx::__normal_iterator<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> > const*, std::vector<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> >, std::allocator<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> > > > >, __gnu_cxx::__normal_iterator<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> > const*, std::vector<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> >, std::allocator<std::unique_ptr<mull::Bitcode, std::default_delete<mull::Bitcode> > > > >, std::vector<int, std::allocator<int> >&, mull::progress_counter&) ()
#4  0x00007ffff79e5d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7824293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

## Expected result

successfully generated mutants

## Version

```
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.10.0-pr855
Commit: 84b5d8b
Date: 23 Apr 2021
LLVM: 11.0.0
```

**Comment by ligurio** [comment]
Problem is gone with latest version of Mull
```
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.10.0-trunk1
Commit: 6ec44bc
Date: 24 May 2021
LLVM: 11.0.0
```
```
       [################################] 170112/170112. Finished in 4619ms
[info] Prepare mutations (threads: 1)
       [################################] 1/1. Finished in 1ms
[info] Cloning functions for mutation (threads: 8)
       [################################] 760/760. Finished in 3919ms
[info] Removing original functions (threads: 8)
       [################################] 760/760. Finished in 280ms
[info] Redirect mutated functions (threads: 8)
       [################################] 760/760. Finished in 21ms
[info] Applying mutations (threads: 1)
       [################################] 14142/14142. Finished in 131ms
[info] Deduplicate mutants (threads: 1)
       [################################] 1/1. Finished in 28ms
[info] Compiling original code (threads: 8)
       [################################] 760/760. Finished in 35286ms
[info] Link mutated program (threads: 1)
       [################################] 1/1. Finished in 1098ms
[info] Mutated executable: postgres.mutated
[info] Total execution time: 47387ms
sergeyb@pony:~/sources/postgres$ 
```
Thanks!
