### ISSUE TITLE
Segmentation fault in  mull::CXXJunkDetector::isJunk

### ISSUE THREAD

**Issue by m42e** [mull-project/mull#894]
Hi,

I am currently experiencing a sporadic SEGFAULT when running mutation tests. 

Environment:
- clang V11.0.0
- ubuntu 20.04
- mull 0.11.1

It sometimes happens that there is a SEGFAULT during junk detection. Here is the call stack:

```
#0  0x0000000002336ab5 in clang::Lexer::getRawToken(clang::SourceLocation, clang::Token&, clang::SourceManager const&, clang::LangOptions const&, bool) ()
#1  0x0000000002337bb4 in clang::Lexer::getLocForEndOfToken(clang::SourceLocation, unsigned int, clang::SourceManager const&, clang::LangOptions const&) ()
#2  0x00000000004ea569 in mull::CXXJunkDetector::isJunk (this=0x7fff1daef4b8, point=0x7f0898023bf0) at ../lib/JunkDetection/CXX/CXXJunkDetector.cpp:243
#3  0x000000000094dfd4 in mull::JunkMutationFilter::shouldSkip (this=0x41e9ee0, point=0x7f0898023bf0) at ../lib/Filters/JunkMutationFilter.cpp:11
#4  0x00000000007c12ba in mull::MutationFilterTask::operator() (this=0x5052cb8, begin=0x7f0898001a70, end=0x7f089803e210, storage=std::vector of length 35, capacity 64 = {...}, counter=...) at ../lib/Parallelization/Tasks/MutationFilterTask.cpp:15
#5  0x000000000049e951 in std::__invoke_impl<void, mull::MutationFilterTask, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<mull::progress_counter> > (__f=..., __args=...,
    __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#6  0x000000000049e7b1 in std::__invoke<mull::MutationFilterTask, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<mull::progress_counter> > (__fn=..., __args=..., __args=...,
    __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#7  0x000000000049e730 in std::thread::_Invoker<std::tuple<mull::MutationFilterTask, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<mull::progress_counter> > >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x5052c98) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#8  0x000000000049e695 in std::thread::_Invoker<std::tuple<mull::MutationFilterTask, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<mull::progress_counter> > >::operator() (
    this=0x5052c98) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#9  0x000000000049e1fe in std::thread::_State_impl<std::thread::_Invoker<std::tuple<mull::MutationFilterTask, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, __gnu_cxx::__normal_iterator<mull::MutationPoint**, std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<std::vector<mull::MutationPoint*, std::allocator<mull::MutationPoint*> > >, std::reference_wrapper<mull::progress_counter> > > >::_M_run (this=0x5052c90) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#10 0x00007f08b0a9fde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f08b0d10609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007f08b08de293 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

If you need further information let me know. I am happy to provide more information and also debug it, if you can give me a hint where to look or what to do.

Thanks

**Comment by ferraith** [comment]
Hello,

I can confirm this issue also for clang-12.
```
devenv:/workspace$ clang --version
Ubuntu clang version 11.0.0-2~ubuntu20.04.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by ferraith** [comment]
I can confirm this issue also with clang-12
```
devenv:/workspace/bin/cmake-Unittest$ clang++ --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.3
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

**Comment by m42e** [comment]
FYI:

After digging a bit deeper and doing some debugging here is some new information:

- It doesn't happen when using only one worker
- Using 16 worker I can reproduce it in 80 to 90% of the runs.
- It always happens at the same location within mull, but in different positions of the code under test

My conclusion would be it is a threading issue, looks like some kind of data race.

**Comment by m42e** [comment]
Where it breaks (within clang):

```
│   458         bool Lexer::getRawToken(SourceLocation Loc, Token &Result,                                                                                                                                                                                   │
│   459                                 const SourceManager &SM,                                                                                                                                                                                             │
│   460                                 const LangOptions &LangOpts,                                                                                                                                                                                         │
│   461                                 bool IgnoreWhiteSpace) {                                                                                                                                                                                             │
│   462           // TODO: this could be special cased for common tokens like identifiers, ')',                                                                                                                                                              │
│   463           // etc to make this faster, if it mattered.  Just look at StrData[0] to handle                                                                                                                                                             │
│   464           // all obviously single-char tokens.  This could use                                                                                                                                                                                       │
│   465           // Lexer::isObviouslySimpleCharacter for example to handle identifiers or                                                                                                                                                                  │
│   466           // something.                                                                                                                                                                                                                              │
│   467                                                                                                                                                                                                                                                      │
│   468           // If this comes from a macro expansion, we really do want the macro name, not                                                                                                                                                             │
│   469           // the token this macro expanded to.                                                                                                                                                                                                       │
│   470           Loc = SM.getExpansionLoc(Loc);                                                                                                                                                                                                             │
│   471           std::pair<FileID, unsigned> LocInfo = SM.getDecomposedLoc(Loc);                                                                                                                                                                            │
│   472           bool Invalid = false;                                                                                                                                                                                                                      │
│   473           StringRef Buffer = SM.getBufferData(LocInfo.first, &Invalid);                                                                                                                                                                              │
│   474           if (Invalid)                                                                                                                                                                                                                               │
│   475             return true;                                                                                                                                                                                                                             │
│   476                                                                                                                                                                                                                                                      │
│   477           const char *StrData = Buffer.data()+LocInfo.second;                                                                                                                                                                                        │
│   478                                                                                                                                                                                                                                                      │
│  >479           if (!IgnoreWhiteSpace && isWhitespace(StrData[0]))                                                                                                                                                                                         │
│   480             return true;                                                                                                                                                                                                                             │
│   481                                                                                                                                                                                                                                                      │
│   482           // Create a lexer starting at the beginning of this token.                                                                                                                                                                                 │
│   483           Lexer TheLexer(SM.getLocForStartOfFile(LocInfo.first), LangOpts,                                                                                                                                                                           │
│   484                          Buffer.begin(), StrData, Buffer.end());                                                                                                                                                                                     │
│   485           TheLexer.SetCommentRetentionState(true);                                                                                                                                                                                                   │
│   486           TheLexer.LexFromRawLexer(Result);                                                                                                                                                                                                          │
│   487           return false;                                                                                                                                                                                                                              │
│   488         }
```
